//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: inboxTypes.proto

package il.ac.technion.cs.softwaredesign;

@kotlin.jvm.JvmName("-initializemessageList")
inline fun messageList(block: il.ac.technion.cs.softwaredesign.MessageListKt.Dsl.() -> kotlin.Unit): il.ac.technion.cs.softwaredesign.MessageList =
  il.ac.technion.cs.softwaredesign.MessageListKt.Dsl._create(il.ac.technion.cs.softwaredesign.MessageList.newBuilder()).apply { block() }._build()
object MessageListKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: il.ac.technion.cs.softwaredesign.MessageList.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: il.ac.technion.cs.softwaredesign.MessageList.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): il.ac.technion.cs.softwaredesign.MessageList = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class MessagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
     */
     val messages: com.google.protobuf.kotlin.DslList<il.ac.technion.cs.softwaredesign.MessageP, MessagesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMessagesList()
      )
    /**
     * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMessages")
    fun com.google.protobuf.kotlin.DslList<il.ac.technion.cs.softwaredesign.MessageP, MessagesProxy>.add(value: il.ac.technion.cs.softwaredesign.MessageP) {
      _builder.addMessages(value)
    }
    /**
     * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
     * @param value The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMessages")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<il.ac.technion.cs.softwaredesign.MessageP, MessagesProxy>.plusAssign(value: il.ac.technion.cs.softwaredesign.MessageP) {
      add(value)
    }
    /**
     * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMessages")
    fun com.google.protobuf.kotlin.DslList<il.ac.technion.cs.softwaredesign.MessageP, MessagesProxy>.addAll(values: kotlin.collections.Iterable<il.ac.technion.cs.softwaredesign.MessageP>) {
      _builder.addAllMessages(values)
    }
    /**
     * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
     * @param values The messages to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMessages")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<il.ac.technion.cs.softwaredesign.MessageP, MessagesProxy>.plusAssign(values: kotlin.collections.Iterable<il.ac.technion.cs.softwaredesign.MessageP>) {
      addAll(values)
    }
    /**
     * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
     * @param index The index to set the value at.
     * @param value The messages to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMessages")
    operator fun com.google.protobuf.kotlin.DslList<il.ac.technion.cs.softwaredesign.MessageP, MessagesProxy>.set(index: kotlin.Int, value: il.ac.technion.cs.softwaredesign.MessageP) {
      _builder.setMessages(index, value)
    }
    /**
     * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMessages")
    fun com.google.protobuf.kotlin.DslList<il.ac.technion.cs.softwaredesign.MessageP, MessagesProxy>.clear() {
      _builder.clearMessages()
    }

  }
}
@kotlin.jvm.JvmSynthetic
inline fun il.ac.technion.cs.softwaredesign.MessageList.copy(block: il.ac.technion.cs.softwaredesign.MessageListKt.Dsl.() -> kotlin.Unit): il.ac.technion.cs.softwaredesign.MessageList =
  il.ac.technion.cs.softwaredesign.MessageListKt.Dsl._create(this.toBuilder()).apply { block() }._build()

