// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inboxTypes.proto

package il.ac.technion.cs.softwaredesign;

public interface InboxPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:il.ac.technion.cs.softwaredesign.InboxP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */
  int getRecordCount();
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */
  boolean containsRecord(
      java.lang.String key);
  /**
   * Use {@link #getRecordMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
  getRecord();
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */
  java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
  getRecordMap();
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */

  /* nullable */
il.ac.technion.cs.softwaredesign.MessageList getRecordOrDefault(
      java.lang.String key,
      /* nullable */
il.ac.technion.cs.softwaredesign.MessageList defaultValue);
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */

  il.ac.technion.cs.softwaredesign.MessageList getRecordOrThrow(
      java.lang.String key);
}
