// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inboxTypes.proto

package il.ac.technion.cs.softwaredesign;

public final class InboxTypes {
  private InboxTypes() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_il_ac_technion_cs_softwaredesign_MessageP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_il_ac_technion_cs_softwaredesign_MessageP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_il_ac_technion_cs_softwaredesign_MessageList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_il_ac_technion_cs_softwaredesign_MessageList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_il_ac_technion_cs_softwaredesign_InboxP_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_il_ac_technion_cs_softwaredesign_InboxP_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_il_ac_technion_cs_softwaredesign_InboxP_RecordEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_il_ac_technion_cs_softwaredesign_InboxP_RecordEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020inboxTypes.proto\022 il.ac.technion.cs.so" +
      "ftwaredesign\032\037google/protobuf/timestamp." +
      "proto\"c\n\010MessageP\022\n\n\002id\030\001 \001(\t\022\014\n\004from\030\002 " +
      "\001(\t\022\017\n\007message\030\003 \001(\t\022,\n\010timeSent\030\004 \001(\0132\032" +
      ".google.protobuf.Timestamp\"K\n\013MessageLis" +
      "t\022<\n\010messages\030\001 \003(\0132*.il.ac.technion.cs." +
      "softwaredesign.MessageP\"\254\001\n\006InboxP\022D\n\006re" +
      "cord\030\001 \003(\01324.il.ac.technion.cs.softwared" +
      "esign.InboxP.RecordEntry\032\\\n\013RecordEntry\022" +
      "\013\n\003key\030\001 \001(\t\022<\n\005value\030\002 \001(\0132-.il.ac.tech" +
      "nion.cs.softwaredesign.MessageList:\0028\001B$" +
      "\n il.ac.technion.cs.softwaredesignP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_il_ac_technion_cs_softwaredesign_MessageP_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_il_ac_technion_cs_softwaredesign_MessageP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_il_ac_technion_cs_softwaredesign_MessageP_descriptor,
        new java.lang.String[] { "Id", "From", "Message", "TimeSent", });
    internal_static_il_ac_technion_cs_softwaredesign_MessageList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_il_ac_technion_cs_softwaredesign_MessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_il_ac_technion_cs_softwaredesign_MessageList_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_il_ac_technion_cs_softwaredesign_InboxP_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_il_ac_technion_cs_softwaredesign_InboxP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_il_ac_technion_cs_softwaredesign_InboxP_descriptor,
        new java.lang.String[] { "Record", });
    internal_static_il_ac_technion_cs_softwaredesign_InboxP_RecordEntry_descriptor =
      internal_static_il_ac_technion_cs_softwaredesign_InboxP_descriptor.getNestedTypes().get(0);
    internal_static_il_ac_technion_cs_softwaredesign_InboxP_RecordEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_il_ac_technion_cs_softwaredesign_InboxP_RecordEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
