// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inboxTypes.proto

package il.ac.technion.cs.softwaredesign;

/**
 * Protobuf type {@code il.ac.technion.cs.softwaredesign.InboxP}
 */
public final class InboxP extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:il.ac.technion.cs.softwaredesign.InboxP)
    InboxPOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InboxP.newBuilder() to construct.
  private InboxP(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InboxP() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InboxP();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InboxP(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              record_ = com.google.protobuf.MapField.newMapField(
                  RecordDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
            record__ = input.readMessage(
                RecordDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            record_.getMutableMap().put(
                record__.getKey(), record__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return il.ac.technion.cs.softwaredesign.InboxTypes.internal_static_il_ac_technion_cs_softwaredesign_InboxP_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetRecord();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return il.ac.technion.cs.softwaredesign.InboxTypes.internal_static_il_ac_technion_cs_softwaredesign_InboxP_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            il.ac.technion.cs.softwaredesign.InboxP.class, il.ac.technion.cs.softwaredesign.InboxP.Builder.class);
  }

  public static final int RECORD_FIELD_NUMBER = 1;
  private static final class RecordDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>newDefaultInstance(
                il.ac.technion.cs.softwaredesign.InboxTypes.internal_static_il_ac_technion_cs_softwaredesign_InboxP_RecordEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                il.ac.technion.cs.softwaredesign.MessageList.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> record_;
  private com.google.protobuf.MapField<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
  internalGetRecord() {
    if (record_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          RecordDefaultEntryHolder.defaultEntry);
    }
    return record_;
  }

  public int getRecordCount() {
    return internalGetRecord().getMap().size();
  }
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */

  @java.lang.Override
  public boolean containsRecord(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetRecord().getMap().containsKey(key);
  }
  /**
   * Use {@link #getRecordMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> getRecord() {
    return getRecordMap();
  }
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> getRecordMap() {
    return internalGetRecord().getMap();
  }
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */
  @java.lang.Override

  public il.ac.technion.cs.softwaredesign.MessageList getRecordOrDefault(
      java.lang.String key,
      il.ac.technion.cs.softwaredesign.MessageList defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> map =
        internalGetRecord().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
   */
  @java.lang.Override

  public il.ac.technion.cs.softwaredesign.MessageList getRecordOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> map =
        internalGetRecord().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetRecord(),
        RecordDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> entry
         : internalGetRecord().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
      record__ = RecordDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, record__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof il.ac.technion.cs.softwaredesign.InboxP)) {
      return super.equals(obj);
    }
    il.ac.technion.cs.softwaredesign.InboxP other = (il.ac.technion.cs.softwaredesign.InboxP) obj;

    if (!internalGetRecord().equals(
        other.internalGetRecord())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetRecord().getMap().isEmpty()) {
      hash = (37 * hash) + RECORD_FIELD_NUMBER;
      hash = (53 * hash) + internalGetRecord().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static il.ac.technion.cs.softwaredesign.InboxP parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(il.ac.technion.cs.softwaredesign.InboxP prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code il.ac.technion.cs.softwaredesign.InboxP}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:il.ac.technion.cs.softwaredesign.InboxP)
      il.ac.technion.cs.softwaredesign.InboxPOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return il.ac.technion.cs.softwaredesign.InboxTypes.internal_static_il_ac_technion_cs_softwaredesign_InboxP_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetRecord();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableRecord();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return il.ac.technion.cs.softwaredesign.InboxTypes.internal_static_il_ac_technion_cs_softwaredesign_InboxP_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              il.ac.technion.cs.softwaredesign.InboxP.class, il.ac.technion.cs.softwaredesign.InboxP.Builder.class);
    }

    // Construct using il.ac.technion.cs.softwaredesign.InboxP.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableRecord().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return il.ac.technion.cs.softwaredesign.InboxTypes.internal_static_il_ac_technion_cs_softwaredesign_InboxP_descriptor;
    }

    @java.lang.Override
    public il.ac.technion.cs.softwaredesign.InboxP getDefaultInstanceForType() {
      return il.ac.technion.cs.softwaredesign.InboxP.getDefaultInstance();
    }

    @java.lang.Override
    public il.ac.technion.cs.softwaredesign.InboxP build() {
      il.ac.technion.cs.softwaredesign.InboxP result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public il.ac.technion.cs.softwaredesign.InboxP buildPartial() {
      il.ac.technion.cs.softwaredesign.InboxP result = new il.ac.technion.cs.softwaredesign.InboxP(this);
      int from_bitField0_ = bitField0_;
      result.record_ = internalGetRecord();
      result.record_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof il.ac.technion.cs.softwaredesign.InboxP) {
        return mergeFrom((il.ac.technion.cs.softwaredesign.InboxP)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(il.ac.technion.cs.softwaredesign.InboxP other) {
      if (other == il.ac.technion.cs.softwaredesign.InboxP.getDefaultInstance()) return this;
      internalGetMutableRecord().mergeFrom(
          other.internalGetRecord());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      il.ac.technion.cs.softwaredesign.InboxP parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (il.ac.technion.cs.softwaredesign.InboxP) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> record_;
    private com.google.protobuf.MapField<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
    internalGetRecord() {
      if (record_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RecordDefaultEntryHolder.defaultEntry);
      }
      return record_;
    }
    private com.google.protobuf.MapField<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
    internalGetMutableRecord() {
      onChanged();;
      if (record_ == null) {
        record_ = com.google.protobuf.MapField.newMapField(
            RecordDefaultEntryHolder.defaultEntry);
      }
      if (!record_.isMutable()) {
        record_ = record_.copy();
      }
      return record_;
    }

    public int getRecordCount() {
      return internalGetRecord().getMap().size();
    }
    /**
     * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
     */

    @java.lang.Override
    public boolean containsRecord(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetRecord().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRecordMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> getRecord() {
      return getRecordMap();
    }
    /**
     * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> getRecordMap() {
      return internalGetRecord().getMap();
    }
    /**
     * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
     */
    @java.lang.Override

    public il.ac.technion.cs.softwaredesign.MessageList getRecordOrDefault(
        java.lang.String key,
        il.ac.technion.cs.softwaredesign.MessageList defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> map =
          internalGetRecord().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
     */
    @java.lang.Override

    public il.ac.technion.cs.softwaredesign.MessageList getRecordOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> map =
          internalGetRecord().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearRecord() {
      internalGetMutableRecord().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
     */

    public Builder removeRecord(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableRecord().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList>
    getMutableRecord() {
      return internalGetMutableRecord().getMutableMap();
    }
    /**
     * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
     */
    public Builder putRecord(
        java.lang.String key,
        il.ac.technion.cs.softwaredesign.MessageList value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableRecord().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .il.ac.technion.cs.softwaredesign.MessageList&gt; record = 1;</code>
     */

    public Builder putAllRecord(
        java.util.Map<java.lang.String, il.ac.technion.cs.softwaredesign.MessageList> values) {
      internalGetMutableRecord().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:il.ac.technion.cs.softwaredesign.InboxP)
  }

  // @@protoc_insertion_point(class_scope:il.ac.technion.cs.softwaredesign.InboxP)
  private static final il.ac.technion.cs.softwaredesign.InboxP DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new il.ac.technion.cs.softwaredesign.InboxP();
  }

  public static il.ac.technion.cs.softwaredesign.InboxP getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InboxP>
      PARSER = new com.google.protobuf.AbstractParser<InboxP>() {
    @java.lang.Override
    public InboxP parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InboxP(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InboxP> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InboxP> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public il.ac.technion.cs.softwaredesign.InboxP getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

