// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inboxTypes.proto

package il.ac.technion.cs.softwaredesign;

public interface MessageListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:il.ac.technion.cs.softwaredesign.MessageList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
   */
  java.util.List<il.ac.technion.cs.softwaredesign.MessageP> 
      getMessagesList();
  /**
   * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
   */
  il.ac.technion.cs.softwaredesign.MessageP getMessages(int index);
  /**
   * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
   */
  java.util.List<? extends il.ac.technion.cs.softwaredesign.MessagePOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .il.ac.technion.cs.softwaredesign.MessageP messages = 1;</code>
   */
  il.ac.technion.cs.softwaredesign.MessagePOrBuilder getMessagesOrBuilder(
      int index);
}
